version: "3.5"

services:
  php_fpm:
      build: .
      container_name: sms_php_fpm
      working_dir: /usr/share/nginx/sms
      networks:
        - sms
      volumes:
          - ./:/usr/share/nginx/sms

  nginx:
      image: nginx:1.15
      container_name: sms_nginx
      working_dir: /usr/share/nginx/sms
      networks:
        - sms
      ports:
          - "8080:80"
      volumes:
          - ./:/usr/share/nginx/sms
          - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
      image: mysql:5.7
      container_name: sms_mysql
      networks:
        - sms
      environment:
        - MYSQL_DATABASE=sms
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_USER=sms
        - MYSQL_PASSWORD=password

networks:
  sms:
    driver: bridge
