auth:
    path: /auth
    defaults: { _controller: AppBundle:Auth:auth }

message_listing:
    path: /message/listing
    defaults: { _controller: AppBundle:Message:listing }

message_send:
    path: /message/send
    defaults: { _controller: AppBundle:Message:send }
